# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

W_Cpp <- function(z, branch) {
    .Call(`_LambertW_W_Cpp`, z, branch)
}

W_delta_Cpp <- function(z, delta) {
    .Call(`_LambertW_W_delta_Cpp`, z, delta)
}

W_delta_alpha_Cpp <- function(z, delta, alpha) {
    .Call(`_LambertW_W_delta_alpha_Cpp`, z, delta, alpha)
}

W_gamma_Cpp <- function(z, gamma, branch) {
    .Call(`_LambertW_W_gamma_Cpp`, z, gamma, branch)
}

#' @rdname estimate-moments
#' @description
#' \code{kurtosis} estimates the fourth central, normalized moment from data.
#' @export
#' 
kurtosis <- function(x) {
    .Call(`_LambertW_kurtosis`, x)
}

lp_norm_Cpp <- function(x, p) {
    .Call(`_LambertW_lp_norm_Cpp`, x, p)
}

lp_norm_complex_Cpp <- function(x, p) {
    .Call(`_LambertW_lp_norm_complex_Cpp`, x, p)
}

normalize_by_tau_Cpp <- function(x, mu_x, sigma_x, inverse) {
    .Call(`_LambertW_normalize_by_tau_Cpp`, x, mu_x, sigma_x, inverse)
}

#' @title Skewness and kurtosis
#' @rdname estimate-moments
#' @description
#' \code{skewness} estimates the third central, normalized moment from data.
#' 
#' @param x a numeric vector.
#' @seealso Corresponding functions in the \pkg{moments} package.
#' @export
skewness <- function(x) {
    .Call(`_LambertW_skewness`, x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_LambertW_RcppExport_registerCCallable`)
})
